<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>C:\o\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>C:\b\$(MSBuildProjectName)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildThisFileDirectory)obj\**;$(MSBuildThisFileDirectory)bin\**;$(MSBuildThisFileDirectory).vs\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>